language: node_js
node_js:
- 'node'
- '6'
- '5'
- '4'

after_success:
- cd build
- git init
- git add .
- git commit -m "The Build"
- git remote add origin git@github.com:pixels-bytes/contentful-travis-github.git
- git push origin master
