language: node_js
node_js:
- 'node'
- '6'
- '5'
- '4'

branches:
  only:
    - develop

script: npm run build

after_success:
- cd build
- git init
- git config user.name "pixels-bytes"
- git config user.email "adam@pixelsandbytes.co"
- git add .
- git commit -m "Deployed to Github Pages"
- git remote add origin git@github.com:pixels-bytes/travis-github-ghpages.git
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

deploy:
  skip_cleanup: true

env:
  global:
    - GH_REF: github.com/pixels-bytes/travis-github-ghpages.git
