language: node_js
node_js:
- 'node'
- '6'
- '5'
- '4'

branches:
  only:
    - develop

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true

env:
  global:
    - GH_REF: github.com/pixels-bytes/contentful-travis-github.git
