language: node_js
node_js:
- 'node'
- '6'
- '5'
- '4'

branches:
  only:
    - develop

script: npm run build

deploy:
  provider: script
  script: scripts/deploy-ghpages.sh
  skip_cleanup: true

env:
  global:
    - GH_REF: github.com/pixels-bytes/contentful-travis-github.git
